#version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - portfolio_net

  ollama:
    image: ghcr.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    command: ["serve"]
    networks:
      - portfolio_net

networks:
  portfolio_net:
    driver: bridge
